name: 3W
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - notebook=6.4.12
  - alive-progress=2.4.1
  - h5py=3.11.0
  - matplotlib=3.6.0
  - natsort=8.2.0
  - pandas=1.5.0
  - plotly=5.13.0
  - pydantic=1.10.4
  - scikit-learn=1.1.2
  - seaborn=0.12.0
  - tslearn=0.5.3.2
  - pandas-profiling=3.6.3
  - numba=0.56.4
  - missingno=0.5.2
  - pyarrow=17.0.0