name: Tests and Coverage
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !dataset/
          sparse-checkout-cone-mode: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Show versions
        run: |
          python --version
          uv --version

      - name: Make helper scripts executable
        run: chmod +x bin/lint bin/test

      - name: Create venv
        run: uv venv .venv

      - name: Install package with dev extras
        run: uv pip install -e .[dev]

      - name: Lint checking
        run: uv run ./bin/lint

      - name: Testing
        run: uv run ./bin/test